name: car_pooling
description: Company carpooling app

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.0

  # Navigation
  go_router: ^14.0.0

  # UI
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.0
  shimmer: ^3.0.0
  intl: ^0.19.0
  image_picker: ^1.1.0
  flutter_rating_bar: ^4.0.0
  badges: ^3.1.0

  # Utils
  shared_preferences: ^2.2.0
  uuid: ^4.4.0
  timeago: ^3.6.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/