// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcqEwwXFvnhiCGt4OEVKZg1VO73sMeP-w',
    appId: '1:902124300718:ios:d7291b121b1d4e092b003f',
    messagingSenderId: '902124300718',
    projectId: 'car-pooling-c242b',
    storageBucket: 'car-pooling-c242b.firebasestorage.app',
    iosBundleId: 'com.example.carpoolingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1JwsZ2ag0bhATjnDUkQ4p97wtJik3WPY',
    appId: '1:902124300718:web:172e6221528e72162b003f',
    messagingSenderId: '902124300718',
    projectId: 'car-pooling-c242b',
    authDomain: 'car-pooling-c242b.firebaseapp.com',
    storageBucket: 'car-pooling-c242b.firebasestorage.app',
    measurementId: 'G-7DZNPHZ2G9',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1JwsZ2ag0bhATjnDUkQ4p97wtJik3WPY',
    appId: '1:902124300718:web:6b70a73c13267b8c2b003f',
    messagingSenderId: '902124300718',
    projectId: 'car-pooling-c242b',
    authDomain: 'car-pooling-c242b.firebaseapp.com',
    storageBucket: 'car-pooling-c242b.firebasestorage.app',
    measurementId: 'G-PZLYRNX4B1',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcqEwwXFvnhiCGt4OEVKZg1VO73sMeP-w',
    appId: '1:902124300718:ios:d7291b121b1d4e092b003f',
    messagingSenderId: '902124300718',
    projectId: 'car-pooling-c242b',
    storageBucket: 'car-pooling-c242b.firebasestorage.app',
    iosBundleId: 'com.example.carpoolingApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN9uL_r70ujCaMWFBZF-PmFF-RBe9QN0A',
    appId: '1:902124300718:android:47c1e4dbdf5b525a2b003f',
    messagingSenderId: '902124300718',
    projectId: 'car-pooling-c242b',
    storageBucket: 'car-pooling-c242b.firebasestorage.app',
  );

}